In [110]:
import os,sys,inspect
sys.path.insert(1, os.path.join(sys.path[0], '..'))

In [111]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [112]:
import env.env as env
import numpy as np

In [113]:
width,height=4,4

In [114]:
grid=env.Grid_game(height,width)

[0, 0]
[3, 3]


In [115]:
grid.set_pos(3,0)

In [116]:
grid.current_state

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [117]:
for i in range(3):
    a,b,c=grid.transition(2)
    print(a)
    print(grid.current_state)
print(a)

False
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]]
False
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]]
True
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]
True


In [118]:
import random

In [119]:
states = [[i, j] for i in range(4) for j in range(4)]


In [120]:
initState = random.choice(states[1:-1])

In [126]:
#One Episodestartx=random.randint(0,3)
Counter=np.zeros((width,height))

#starty=0
#startx=3

Returns=np.zeros((height,width))
rewards=0
k=0.8

y,x=grid.player.curpos
Counter[y][x]+=1
num_samples=10000
for i in range(num_samples):
    starty=random.randint(0,3)
    startx=random.randint(0,3)
    grid.set_pos(starty,startx)
    iteration=0
    rewards=0
    while(not grid.state):
        iteration+=1
        state,cur_state,reward=grid.transition()
        y,x=grid.player.curpos
        Counter[y][x]+=1
        if not state:
            
            rewards+=k**(iteration)*reward
            Returns[y][x]+=rewards
    
print(Returns/Counter)



[[ 0.         -3.29058717 -3.31482418 -3.34648647]
 [-3.29670915 -3.29611413 -3.30681556 -3.32175826]
 [-3.31472053 -3.30262726 -3.2811277  -3.28003798]
 [-3.3333682  -3.32397376 -3.30188134  0.        ]]


In [123]:
Counter

array([[1.0000e+00, 8.1250e+03, 1.1964e+04, 1.3582e+04],
       [8.1960e+03, 1.0745e+04, 1.2013e+04, 1.2080e+04],
       [1.1637e+04, 1.1727e+04, 1.0566e+04, 8.2290e+03],
       [1.2980e+04, 1.1675e+04, 7.8110e+03, 0.0000e+00]])

In [86]:
Counter

array([[1.0000e+00, 1.8126e+04, 2.7854e+04, 3.1308e+04],
       [1.7870e+04, 2.4914e+04, 3.0561e+04, 3.2931e+04],
       [2.7463e+04, 3.0409e+04, 3.3237e+04, 3.4772e+04],
       [3.1476e+04, 3.3248e+04, 3.5038e+04, 3.5834e+04]])

In [57]:
rewards/2.0

-0.5

In [17]:
grid.state

True

In [ ]:
grid.current_state