In [82]:

import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.nn.init as init
import torch.optim as optim
import random

In [83]:
width,height=4,4

In [84]:
import os,sys,inspect
sys.path.insert(1, os.path.join(sys.path[0], '..'))

In [85]:
%load_ext autoreload
%autoreload 2
import env.env as env
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [119]:
value_approximator=nn.Sequential(nn.Linear(2,4),nn.Linear(4,1))
states = [[i, j] for i in range(4) for j in range(4)]

In [120]:
state_tensor=torch.tensor(grid.current_state.flatten()[:]).float()

In [121]:
val=value_approximator(state_tensor)


RuntimeError: size mismatch, m1: [1 x 16], m2: [2 x 4] at C:\cb\pytorch_1000000000000\work\aten\src\TH/generic/THTensorMath.cpp:41

In [122]:
loss=nn.MSELoss()

In [90]:
optimizer = optim.SGD(value_approximator.parameters(), lr=0.01)

In [123]:
#One Episodestartx=random.randint(0,3)
grid=env.Grid_game(height,width)
Counter=np.zeros((width,height))
#starty=0
#startx=3
history=[]
Returns=np.zeros((height,width))
rewards=0
k=0.8

y,x=grid.player.curpos

num_episodes=10000


for i in range(num_episodes):
    state_list=[]
    starty,startx = random.choice(states[1:-1])
    grid.set_pos(starty,startx)
    iteration=0
    rewards=0
    if num_episodes % 1000:
        print(mse_loss)
    while(not grid.state):
        value_approximator.zero_grad()
        
        oldpos=grid.player.curpos[:]
        oldstate=torch.tensor(oldpos).float()
        iteration+=1
        state,cur_state,reward,_=grid.transition()
        curpos=grid.player.curpos[:]
        newstate=torch.tensor(curpos).float()
        Counter[curpos[0]][curpos[1]]+=1
        
        val_newstate=-1+k*value_approximator(newstate)
        val_oldstate=value_approximator(oldstate)
        
        mse_loss=loss(val_oldstate,val_newstate)
        mse_loss.backward()
        optimizer.step()
        break
        
    history.append(grid.vst[:].copy())
    
    

In [107]:
value_approximator.weight.grad

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [108]:
value_approximator.weight

Parameter containing:
tensor([[ 0.2267, -0.2836, -0.2281, -0.2025, -0.1866, -0.2531, -0.2271, -0.2060,
         -0.1395, -0.2013, -0.2653, -0.2768, -0.1904, -0.1603, -0.2781,  0.1775]],
       requires_grad=True)

In [109]:
val=value_approximator(newstate)

In [110]:
value_approximator.weight.grad

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [111]:
val.backward()

In [114]:
value_approximator.weight.grad

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [125]:
for i in range(4):
    for j in range(4):
        grid.vst[i][j]=value_approximator(torch.tensor([i,j]).float())

In [126]:
grid.vst

array([[-0.33714992, -0.8507424 , -1.36433506, -1.8779273 ],
       [-0.83484489, -1.34843731, -1.86202979, -2.37562251],
       [-1.3325398 , -1.84613228, -2.35972476, -2.87331748],
       [-1.83023477, -2.34382749, -2.85741997, -3.37101221]])