![alt text](../img/PolicyIteration.png "Title")


# Bellman's expectation backup

In [130]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [131]:
import os,sys,inspect
sys.path.insert(1, os.path.join(sys.path[0], '..'))

In [132]:
import env.env as env
import numpy as np

In [133]:
grid=env.Grid_game(4,4)

[0, 0]
[3, 3]


In [134]:
def single_state_update(y,x,grid,num_actions=4):
    summation=0
    for action_index,policy_as in enumerate(grid.policy[0:num_actions,y,x]):
        grid.set_pos(y,x)
        s_1=grid.transition(force=True,action=action_index)[1]

        summation+=policy_as*(grid.fix_reward_val+grid.vst[s_1[0]][s_1[1]])
    return summation    
    

In [135]:
for k in range(7):
    #print(grid.vst)
    values=np.empty_like(grid.vst)
    for y in range(4):
        for x in range(4):
            values[y,x]=single_state_update(y,x,grid)
    grid.vst=values
print(grid.vst)

[[ 0.         -4.734375   -6.27734375 -6.65527344]
 [-4.734375   -5.89941406 -6.36425781 -6.27734375]
 [-6.27734375 -6.36425781 -5.89941406 -4.734375  ]
 [-6.65527344 -6.27734375 -4.734375    0.        ]]


![alt text](../img/ValueIteration.png "Title")



In [136]:
grid=env.Grid_game(6,6,TERMIN_STATE_POS =[[0,0],[3,3]])

[0, 0]
[3, 3]


In [137]:
def single_state_update_value(y,x,grid,num_actions=4):
    value_list=[]
    for action_index,policy_as in enumerate(grid.policy[0:num_actions,y,x]):
        grid.set_pos(y,x)
        s_1=grid.transition(force=True,action=action_index)[1]
        value_list.append((grid.fix_reward_val+grid.vst[s_1[0]][s_1[1]]))
    return max(value_list)
    

In [138]:
for k in range(100):
    #
    values=np.empty_like(grid.vst)
    for y in range(6):
        for x in range(6):
            values[y,x]=single_state_update_value(y,x,grid)
    grid.vst=values
    for i in grid.TERMINAL_STATE_POS:
        grid.vst[i[0]][i[1]]=0
    
print(grid.vst)    

[[ 0. -1. -2. -3. -4. -5.]
 [-1. -2. -3. -2. -3. -4.]
 [-2. -3. -2. -1. -2. -3.]
 [-3. -2. -1.  0. -1. -2.]
 [-4. -3. -2. -1. -2. -3.]
 [-5. -4. -3. -2. -3. -4.]]
