In [193]:
import os,sys,inspect
sys.path.insert(1, os.path.join(sys.path[0], '..'))
import random

In [194]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [195]:
import env.env as env
import numpy as np

In [196]:
height,width=4,4

In [197]:
grid=env.Grid_game(height,width)

from utils.function import set_mu_policy
    

In [198]:
behavior_policy=set_mu_policy(grid)

In [199]:
states = [[i, j] for i in range(4) for j in range(4)]

In [200]:
grid=env.Grid_game(height,width)
Counter=np.zeros((width,height))
#starty=0
#startx=3
history=[]

Returns=np.zeros((height,width))
rewards=0
k=0.8
alpha=0.001
epislon_counter=0
y,x=grid.player.curpos

num_episodes=10000
for i in range(num_episodes):
    counter=0
    state_list=[]
    action_list=[]
    starty,startx = random.choice(states[1:-1])
    grid.set_pos(starty,startx)
    iteration=0
    rewards=0
    state_list.append(grid.player.curpos[:])
    while(not grid.state):
        oldpos=grid.player.curpos[:]
        iteration+=1
    
        pos_action_list = np.argwhere(behavior_policy[0:4,oldpos[0],oldpos[1]] == np.amax(behavior_policy[0:4,oldpos[0],oldpos[1]])).tolist()
        action_index=random.choice(pos_action_list)[0]
        
        pos_target_list = np.argwhere(grid.ast[0:4,oldpos[0],oldpos[1]] == np.amax(grid.ast[0:4,oldpos[0],oldpos[1]])).tolist()
        target_policy=random.choice(pos_target_list)[0]
        
        if np.random.rand() <0.01:
            epislon_counter+=1
            action_index=np.random.randint(0,4)
        state,cur_state,reward,action=grid.transition(action_index)
        action=int(action)
        curpos=grid.player.curpos[:]
        Counter[curpos[0]][curpos[1]]+=1
        grid.ast[action][oldpos[0]][oldpos[1]]=grid.ast[action][oldpos[0]][oldpos[1]]+\
                                                alpha*((-1+k*np.max(grid.ast[0:4,curpos[0],curpos[1]]))-grid.ast[action][oldpos[0]][oldpos[1]])
        grid.ast=np.round(grid.ast,3)
        counter +=1


    history.append(grid.vst[:].copy())
        

In [201]:
grid.ast

array([[[-1.   , -1.003, -1.003, -1.   ],
        [-1.3  , -1.003, -1.181, -1.007],
        [-1.306, -1.302, -1.007, -1.011],
        [-1.302, -1.016, -1.306, -1.   ]],

       [[-1.   , -1.008, -1.003, -1.301],
        [-1.011, -1.542, -1.183, -1.309],
        [-1.003, -1.312, -1.323, -1.3  ],
        [-1.006, -1.014, -1.028, -1.   ]],

       [[-1.   , -1.003, -1.002, -1.001],
        [-1.007, -1.002, -1.195, -1.003],
        [-1.002, -1.306, -1.309, -1.012],
        [-1.312, -1.323, -1.03 , -1.   ]],

       [[-1.   , -1.3  , -1.303, -1.302],
        [-1.008, -1.306, -1.165, -1.001],
        [-1.002, -1.302, -1.012, -1.017],
        [-1.002, -1.014, -1.312, -1.   ]]])

In [202]:
y=1
x=3
pos_action_list = np.argwhere(behavior_policy[0:4,y,x] == np.amax(behavior_policy[0:4,y,x])).tolist()
action_index=random.choice(pos_action_list)[0]
print(action_index)

1


In [203]:
y=1
x=1
pos_action_list = np.argwhere(grid.ast[0:4,y,x] == np.amax(grid.ast[0:4,y,x])).tolist()
action_index=random.choice(pos_action_list)[0]
print(action_index)

2


In [207]:
behavior_policy

array([[[0.5 , 0.  , 0.  , 0.  ],
        [1.  , 0.  , 0.25, 0.  ],
        [1.  , 0.25, 0.  , 0.  ],
        [0.5 , 0.  , 0.5 , 0.  ]],

       [[0.  , 0.  , 0.  , 0.5 ],
        [0.  , 0.5 , 0.25, 1.  ],
        [0.  , 0.25, 0.5 , 1.  ],
        [0.  , 0.  , 0.  , 0.5 ]],

       [[0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.25, 0.  ],
        [0.  , 0.25, 0.5 , 0.  ],
        [0.5 , 1.  , 0.  , 0.5 ]],

       [[0.5 , 1.  , 1.  , 0.5 ],
        [0.  , 0.5 , 0.25, 0.  ],
        [0.  , 0.25, 0.  , 0.  ],
        [0.  , 0.  , 0.5 , 0.  ]]])

In [208]:
grid.current_state

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [209]:
grid=env.Grid_game(height,width)


In [210]:
grid.current_state

array([[-1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.]])

In [ ]:
class value_approximate